INSERT into fund_codes (name,fund_code) VALUES ('Agelasto Family Library Fund for Special Collections', 'AGELASTO-ER00660'),
('Alfred Henry Byrd Library Fund', 'BYRD-ER00581'),
('American Literature Library Fund', 'AMLIT-ER00651'),
('Battestin Fund for 18th Century British Literature', 'BATTESTIN-DR00516'),
('Books Arts Press Fund for the University of Virginia Library', 'BOOKARTS-ER00700'),
('Bradley Hunt, Meredith Strohm, and Bradford Macon Gunter Collection of English and American Literature Fund', 'GUNTER-ER00654'),
('C. Venable Minor Endowment Fund', 'MINOR-ER00649'),
('Casa del Greco Library Fund', 'DELGRECO-ER00650'),
('Charles Julian Bishko Library Excellence Fund', 'BISHKO-DR01376'),
('Charles Locke Purchase Fund', 'LOCKE-ER00569'),
('Class Of 1930 Library Fund', 'CLASS-OF-30-ER00583'),
('Class Of 1940 Book Fund', 'CLASS-OF-40-ER00584'),
('Class Of 1952 Library Fund', 'CLASS-OF-52-ER00585'),
('Class Of 1960 Book Fund', 'CLASS-OF-60-ER00607'),
('Class Of 1961 Book', 'CLASS-OF-61-ER00608'),
('Class Of 1964 Library Fund', 'CLASS-OF-64-ER00612'),
('Clifton Waller Barrett Library Fund', 'SC-PRB-M'),
('Colgate W. Darden, Jr. Book Fund', 'DARDEN-ER00586'),
('Colonial Dames Fund', 'SG-COL-DAMES-DR01374'),
('Dorothy Smith Berkeley and Edmund Berkeley Natural History Endowed Fund', 'BERKELEY-ER00643'),
('Douglas Hamilton Gordon Library Fund', 'GORDON-ER00590'),
('E. C. Coles Library Fund', 'COLES-UPRESS-ER00588'),
('Ellen Bayard Weedon Foundation Gift Fund', 'WEEDON-DR01378'),
('Ellen Gilliam Perry Book Fund', 'PERRY-ER00572'),
('Gilbert Schuyler Bahn Endowed Fund', 'BAHN-ER00644'),
('Hatfield Chappell Fund', 'HATFIELD-CH-ER00629'),
('Henry S. Gordon Book Fund', 'GORDON-HENRY-ER00633'),
('International Studies Library Fund', 'INTL-STUDIES-ER00593'),
('James A. Myatt Memorial Fund', 'MYATT-ER00618'),
('James E. Kinard Library Fund For History', 'KINARD-ER00661'),
('James S. Helms Memorial Fund', 'HELMS-ER00606'),
('Jean S. Kane Library Fund', 'KANE-ER00704'),
('John C. Metcalf Memorial Fund', 'METCALF-ER00597'),
('John Cook Wyllie Memorial Book Fund', 'WYLLIE-ER00621'),
('Library Associates Endowment for Rare Books and Manuscripts', 'ASSOCIATES-ER00570'),
('Linton R. Massey Fund for the William Faulkner Collection', 'MASSEY-ER00626'),
('Louis Henry and Marguerite A. Cohn Ernest Hemingway Memorial Collection', 'COHN-HEMING-ER00571'),
('Marion duPont Scott Fund', 'SCOTT-ER00573'),
('Martin C. and Ruthe R. Battestin Library Fund', 'BATTESTIN-ER02018'),
('Mary Alice Kraehe Memorial Fund for Books on Africa', 'KRAEHE-ER00657'),
('Middle Atlantic Chapter of American Rhododendron Society', 'RHODODENDRON-ER00634'),
('Montgomery Memorial Fund', 'MONTGOMERY-ER00598'),
('Nellie and Pinckney Harrison Fund', 'HARRISON-ER00619'),
('Oron J. Hale Fund', 'HALE-OJ-ER00639'),
('Price-Taylor Library Fund', 'PRICE-TAYLOR-ER00613'),
('R. H. Webb Book Fund', 'WEBB-ER00605'),
('Ray W. Frantz, Jr. 19th Century British Literature Fund', 'FRANTZ-ER00640'),
('Raymond C. Bice, Jr., Library Fund', 'BICE-ER00688'),
('Ribble-Henry Fielding and his Contemporaries Fund', 'RIBBLE-DR01375'),
('Robert Taylor Collection Fund', 'TAYLOR-RBT-ER00609'),
('Robert and Virginia Tunstall Trust Fund', 'TUNSTALL-ER00631'),
('Thomas G. and Dorothy H. DeShazo Library Fund', 'DESHAZO-ER02042'),
('Tracy W. McGregor Library Endowed Fund', 'MCGREGOR-ER00642'),
('Urban Joseph Peters Rushton Memorial Book Fund', 'RUSHTON-ER00602'),
('W. Braden and Kathryn K. Kerchof Library Fund', 'KERCHOF-ER01879'),
('Walter S. McIlhenny Endowment', 'MCILHENNY-ER00638'),
('Warren Fulton Chauncey Fund', 'CHAUNCEY-ER01747'),
('Weatherly Library Fund', 'WEATHERLY-ER00646'),
('William B. O''neal Book Fund', 'ONEAL-SC-ER00630'),
('William Faulkner Foundation Fund', 'FAULKNER-ER00624'),
('William G. Suhling, Jr., and William G. Suhling III Library Fund', 'SUHLING-ER00652'),
('William H. Runge Memorial Fund for Southern History', 'RUNGEA-ER00568'),
('William Newton Hale Library Fund for Architecture', 'HALE-WM-ER00667'),
('William and Elizabeth Millhiser Morris Rare Books Endowment Fund', 'MORRIS-ER00659'),
('Wilson Gee Library Fund', 'GEE-ER00589'),
('Wilson Gee Memorial Fund', 'GEE-SO-ER00589');