BEGIN;
ALTER TABLE collections ADD COLUMN title VARCHAR (255) default '';
UPDATE collections set title='Daily Progress Digitized Microfilm' where id=1;
UPDATE collections set title='Agelasto Family Library Fund for Special Collections' where id=2;
UPDATE collections set title='Alfred Henry Byrd Library Fund' where id=3;
UPDATE collections set title='American Literature Library Fund' where id=4;
UPDATE collections set title='Battestin Fund for 18th Century British Literature' where id=5;
UPDATE collections set title='Books Arts Press Fund for the University of Virginia Library' where id=6;
UPDATE collections set title='Bradley Hunt, Meredith Strohm, and Bradford Macon Gunter Collection of English and American Literature Fund' where id=7;
UPDATE collections set title='C. Venable Minor Endowment Fund' where id=8;
UPDATE collections set title='Casa del Greco Library Fund' where id=9;
UPDATE collections set title='Charles Julian Bishko Library Excellence Fund' where id=10;
UPDATE collections set title='Charles Locke Purchase Fund' where id=11;
UPDATE collections set title='Class Of 1930 Library Fund' where id=12;
UPDATE collections set title='Class Of 1940 Book Fund' where id=13;
UPDATE collections set title='Class Of 1952 Library Fund' where id=14;
UPDATE collections set title='Class Of 1960 Book Fund' where id=15;
UPDATE collections set title='Class Of 1961 Book' where id=16;
UPDATE collections set title='Class Of 1964 Library Fund' where id=17;
UPDATE collections set title='Clifton Waller Barrett Library Fund' where id=18;
UPDATE collections set title='Colgate W. Darden, Jr. Book Fund' where id=19;
UPDATE collections set title='Colonial Dames Fund' where id=20;
UPDATE collections set title='Dorothy Smith Berkeley and Edmund Berkeley Natural History Endowed Fund' where id=21;
UPDATE collections set title='Douglas Hamilton Gordon Library Fund' where id=22;
UPDATE collections set title='E. C. Coles Library Fund' where id=23;
UPDATE collections set title='Ellen Bayard Weedon Foundation Gift Fund' where id=24;
UPDATE collections set title='Ellen Gilliam Perry Book Fund' where id=25;
UPDATE collections set title='Gilbert Schuyler Bahn Endowed Fund' where id=26;
UPDATE collections set title='Hatfield Chappell Fund' where id=27;
UPDATE collections set title='Henry S. Gordon Book Fund' where id=28;
UPDATE collections set title='International Studies Library Fund' where id=29;
UPDATE collections set title='James A. Myatt Memorial Fund' where id=30;
UPDATE collections set title='James E. Kinard Library Fund For History' where id=31;
UPDATE collections set title='James S. Helms Memorial Fund' where id=32;
UPDATE collections set title='Jean S. Kane Library Fund' where id=33;
UPDATE collections set title='John C. Metcalf Memorial Fund' where id=34;
UPDATE collections set title='John Cook Wyllie Memorial Book Fund' where id=35;
UPDATE collections set title='Library Associates Endowment for Rare Books and Manuscripts' where id=36;
UPDATE collections set title='Linton R. Massey Fund for the William Faulkner Collection' where id=37;
UPDATE collections set title='Louis Henry and Marguerite A. Cohn Ernest Hemingway Memorial Collection' where id=38;
UPDATE collections set title='Marion duPont Scott Fund' where id=39;
UPDATE collections set title='Martin C. and Ruthe R. Battestin Library Fund' where id=40;
UPDATE collections set title='Mary Alice Kraehe Memorial Fund for Books on Africa' where id=41;
UPDATE collections set title='Middle Atlantic Chapter of American Rhododendron Society' where id=42;
UPDATE collections set title='Montgomery Memorial Fund' where id=43;
UPDATE collections set title='Nellie and Pinckney Harrison Fund' where id=44;
UPDATE collections set title='Oron J. Hale Fund' where id=45;
UPDATE collections set title='Price-Taylor Library Fund' where id=46;
UPDATE collections set title='R. H. Webb Book Fund' where id=47;
UPDATE collections set title='Ray W. Frantz, Jr. 19th Century British Literature Fund' where id=48;
UPDATE collections set title='Raymond C. Bice, Jr., Library Fund' where id=49;
UPDATE collections set title='Ribble-Henry Fielding and his Contemporaries Fund' where id=50;
UPDATE collections set title='Robert Taylor Collection Fund' where id=51;
UPDATE collections set title='Robert and Virginia Tunstall Trust Fund' where id=52;
UPDATE collections set title='Thomas G. and Dorothy H. DeShazo Library Fund' where id=53;
UPDATE collections set title='Tracy W. McGregor Library Endowed Fund' where id=54;
UPDATE collections set title='Urban Joseph Peters Rushton Memorial Book Fund' where id=55;
UPDATE collections set title='W. Braden and Kathryn K. Kerchof Library Fund' where id=56;
UPDATE collections set title='Walter S. McIlhenny Endowment' where id=57;
UPDATE collections set title='Warren Fulton Chauncey Fund' where id=58;
UPDATE collections set title='Weatherly Library Fund' where id=59;
UPDATE collections set title='William B. O''neal Book Fund' where id=60;
UPDATE collections set title='William Faulkner Foundation Fund' where id=61;
UPDATE collections set title='William G. Suhling, Jr., and William G. Suhling III Library Fund' where id=62;
UPDATE collections set title='William H. Runge Memorial Fund for Southern History' where id=63;
UPDATE collections set title='William Newton Hale Library Fund for Architecture' where id=64;
UPDATE collections set title='William and Elizabeth Millhiser Morris Rare Books Endowment Fund' where id=65;
UPDATE collections set title='Wilson Gee Library Fund' where id=66;
UPDATE collections set title='Wilson Gee Memorial Fund' where id=67;
COMMIT;