BEGIN;
INSERT into collections (id,filter_name,title) VALUES
   (68, 'FilterBookplate', 'Caplin Monographs and Serials'),
   (69, 'FilterBookplate', 'Dillard Monographs and Serials'),
   (70, 'FilterBookplate', 'Dorthea Lane Cutts'),
   (71, 'FilterBookplate', 'Elise Sieker Walker Library Fund'),
   (72, 'FilterBookplate', 'Endow a book'),
   (73, 'FilterBookplate', 'Endowment Monographs and Serials'),
   (74, 'FilterBookplate', 'Farmer Monographs and Serials'),
   (75, 'FilterBookplate', 'Fox Monographs and Serials'),
   (76, 'FilterBookplate', 'Herd Monographs and Serials'),
   (77, 'FilterBookplate', 'Hobbie Monographs and Serials'),
   (78, 'FilterBookplate', 'Jefferson Legal Collection'),
   (79, 'FilterBookplate', 'John Ritchie Fund'),
   (80, 'FilterBookplate', 'Judge Watrous Monographs and Serials'),
   (81, 'FilterBookplate', 'Klaus'),
   (82, 'FilterBookplate', 'NEH Monographs and Serials'),
   (83, 'FilterBookplate', 'Preston Fox monographs and serials'),
   (84, 'FilterBookplate', 'Sheppe Monographs and Serials'),
   (85, 'FilterBookplate', 'White Monographs and Serials');

INSERT into images (collection_id, alt_text, title, width, height, filename) VALUES
   (68, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (69, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (70, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (71, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (72, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (73, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (74, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (75, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (76, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (77, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (78, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (79, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (80, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (81, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (82, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (83, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (84, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (85, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' );

INSERT into images (collection_id, alt_text, title, width, height, filename) VALUES
   (2, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (4, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (5, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (6, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (18, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (19, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (30, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (31, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (34, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (37, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (38, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (39, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (40, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (41, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (43, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (45, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (46, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (49, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (51, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (53, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (56, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (58, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (60, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (61, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' ),
   (65, 'University of Virginia Library', 'University of Virginia Library', 912, 1288, 'generic-bookplate.png' );

COMMIT;